// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeXd6dVcqDjDWxb1UScQ4S5z6hzciB0YE',
    appId: '1:390433438263:web:8721930b35719bc2151db2',
    messagingSenderId: '390433438263',
    projectId: 'flutter-mvvm-3f75a',
    authDomain: 'flutter-mvvm-3f75a.firebaseapp.com',
    storageBucket: 'flutter-mvvm-3f75a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSByHMlRTGE2TXTxqTaJJ5xeryJ5ozfM8',
    appId: '1:390433438263:android:36e6f8bf7e58b98f151db2',
    messagingSenderId: '390433438263',
    projectId: 'flutter-mvvm-3f75a',
    storageBucket: 'flutter-mvvm-3f75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGvcRSLUy_egP1Yes7EsikTUfHUGq4A8',
    appId: '1:390433438263:ios:f60f8cae8d5ca76e151db2',
    messagingSenderId: '390433438263',
    projectId: 'flutter-mvvm-3f75a',
    storageBucket: 'flutter-mvvm-3f75a.firebasestorage.app',
    iosBundleId: 'com.example.flutterGamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGvcRSLUy_egP1Yes7EsikTUfHUGq4A8',
    appId: '1:390433438263:ios:f60f8cae8d5ca76e151db2',
    messagingSenderId: '390433438263',
    projectId: 'flutter-mvvm-3f75a',
    storageBucket: 'flutter-mvvm-3f75a.firebasestorage.app',
    iosBundleId: 'com.example.flutterGamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeXd6dVcqDjDWxb1UScQ4S5z6hzciB0YE',
    appId: '1:390433438263:web:216be38bf535ac89151db2',
    messagingSenderId: '390433438263',
    projectId: 'flutter-mvvm-3f75a',
    authDomain: 'flutter-mvvm-3f75a.firebaseapp.com',
    storageBucket: 'flutter-mvvm-3f75a.firebasestorage.app',
  );
}
